### ISSUE TITLE
Unsafe stuff is marked safe

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-gc#1]
Because the plugin infra doesn't let us derive unsafe functions (I will fix this)

Tracking issue to mark the places this needs to be fixed in-code

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/25524

**Comment by Manishearth** [comment]
We can fix this in the next nightly, by reverting the deunsafeification and then adding `is_unsafe: true` and `false` fields to the relevant `MethodDef`s [here](https://github.com/Manishearth/rust-gc/blob/master/gc_plugin/src/lib.rs#L35)

**Comment by mystor** [comment]
Trace::trace & Trace::unroot should be unsafe. I'm undecided as to whether Trace::root should.

Both trace and unroot can cause visible references to be freed, so they are certainly unsafe.

Root is a footgun, but doesn't technically violate memory safety in the current impl. Rather it will either throw, or effectively mem::forget a value. However, it does violate some invariants which I would like to keep so that I can more easily make changes to the system (and which may eventually be necessary for memory safety), so it probably should be unsafe.

**Comment by mystor** [comment]
Fixed in 8e36594d47baf0388c0099a4c27152b21cbd03e4.

**Comment by Manishearth** [comment]
This is a good idea. A lot of the rust community frowns at using unsafe for other footgubs (I don't); but either way until we're finished we don't want changing invariants to make it unsafe without us noticing.
