### ISSUE TITLE
Add UnsafeGcCell

### ISSUE THREAD

**Issue by sisungo** [Manishearth/rust-gc#120]
GcCell checks borrow, just like RefCell. However, sometimes it's necessary to avoid borrow checking, like UnsafeCell. So there can be a cell without borrow checking and implements Trace.

**Comment by Manishearth** [comment]
making `UnsafeCell` `Trace` (or a new type like it) is a complete non-starter because `Gc<UnsafeCell<T>>` can then be safely constructed and used and the implicit trace operations will always be unsafe.

If you need this, you should create your own type that _contains_ an `UnsafeCell`, and skip over it in the `Trace` implementation, or handle `Trace` based on your constraints.
